### ISSUE TITLE
Filter or sort by difficulty

### ISSUE THREAD

**Issue by Lonami** [1milligram/html-dom#122]
I found the `advanced` tips really fun. Maybe it's useful to add a way to filter for how hard it is to do something, or instead a way to sort by difficulty. This way people can answer "what basic things can I do with Vanilla JS" at a glance, or satisfy the curiosity of people like me.

**Comment by elkarouani** [comment]
I guess this issue will not be existing after the posts was grouped by difficulty !

**Comment by phuoc-ng** [comment]
You are right, @elkarouani 👍
