### ISSUE TITLE
add: get relative mouse position with CSS transforms

### ISSUE THREAD

**Issue by n1ru4l** [1milligram/html-dom#167]
https://github.com/ombr/referentiel/blob/master/src/referentiel.coffee

**Comment by elkarouani** [comment]
The link need to be updated !

**Comment by n1ru4l** [comment]
https://github.com/ombr/referentiel/blob/master/src/referentiel.js

Not sure what I meant here actually, so gonna close this

**Comment by elkarouani** [comment]
That's OK @n1ru4l, you can reopen this issue any time you want to add more details about it.
