### ISSUE TITLE
Old design

### ISSUE THREAD

**Issue by LeCodeCo** [1milligram/html-dom#218]
I was wondering which commit the design was changed in? I tried looking but I couldn't find it.

I miss this old design (but with the search box), and I wanted to run it locally.
![image](https://user-images.githubusercontent.com/20425781/121334621-b9935680-c911-11eb-9760-b479bdb9c2b1.png)

**Comment by Gilipe** [comment]
Was also curious about this?

**Comment by phuoc-ng** [comment]
See the new version https://htmldom.dev/
Fixed in #223
